#!/bin/bash

set -e

source .env.sh

./use-native-libs

cd src

funcs=$3
if [ "$funcs" == "" ]; then
  funcs="logatron"
  funcs="$funcs transform"
fi

for f in $funcs; do
  serverless deploy function -f $f
done

cd -
./restore-vendored
